FROM alpine-jdk:base
MAINTAINER swastika
COPY files/employeeconfigserver.jar /opt/lib/
RUN mkdir /root/config-repo
COPY config-repo /root/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/employeeconfigserver.jar"]
VOLUME /var/lib/config-repo
EXPOSE 8888
